version: "3.9"

services:
  web:
    build:
      context: .
      args:
        SECRET_KEY: 5b52OUpj1lN1c6cYU2-OG1NJtI3Wp0qm3nor7fAxFmwTaa7Z_roX3OHWpGm4VdNCMhw
    env_file: .env
    volumes:
      - ./:/opt/webapp
    ports:
      - "8000:8000"
  postgres:
    environment:
      POSTGRES_PASSWORD: test1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"

volumes: 
  postgres-data: