# Generated by Django 2.2.28 on 2022-10-06 00:35

from django.db import migrations, models


def allPlans(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Plan = apps.get_model("home", "Plan")

    plan1 = {
        "name": "Free",
        "description": "Free ($0)",
        "price": "0"            
    }

    Plan.objects.update_or_create(defaults=plan1, id=1)

    plan2 = {
        "name": "Standard",
        "description": "Standard ($10)",
        "price": "10"            
    }
    Plan.objects.update_or_create(defaults=plan2, id=2)

    plan3 = {
        "name": "Pro",
        "description": "Pro ($25)",
        "price": "25"            
    }

    Plan.objects.update_or_create(defaults=plan3, id=3)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('framework', models.CharField(max_length=100)),
                ('domain_name', models.CharField(max_length=255)),                         
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.IntegerField()),
                ('app', models.IntegerField()),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(allPlans),
    ]